version: '3.7'

services:
  tebot:
    image: tebot
    container_name: tebot
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    ports:
      - 3000:3000
